name: Build linux (aarch64)

on:
  pull_request:
  push:

jobs:
  build:
    strategy:
      matrix:
        include:
          - arch: aarch64
            distro: ubuntu20.04
        mode: [debug, release]
        fail-fast: false

    runs-on: ubuntu-20.04
    if: "!contains(github.event.head_commit.message, 'ci skip')"

    steps:
    - uses: actions/checkout@v2
    - uses: uraimo/run-on-arch-action@v2.1.1
      name: Virtualize & Build
      with:
        arch: ${{ matrix.arch }}
        distro: ${{ matrix.distro }}
        githubToken: ${{ github.token }}
        run: |
          apt-get update && apt-get upgrade -y
          DEBIAN_FRONTEND=noninteractive apt-get install -y git build-essential gcc g++ bash curl unzip m4 pkg-config cmake autoconf automake
          git submodule sync --recursive
          git submodule update --init --force --recursive --depth=1
          bash <(curl -fsSL https://xmake.io/shget.text)
          source ~/.xmake/profile
          sed -i s/x64/aarch64/g xmake.lua
          xmake config --root --arch=arm64-v8a --mode=${{ matrix.mode }} --yes
          xmake
          xmake install -o packaged

    # Upload artifacts
    - uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.os }}-${{ matrix.arch }}-${{ matrix.mode }}
        path: packaged/bin/**
